### ISSUE TITLE
Output instructions in cluster_manager.sh inconsistent with guide

### ISSUE THREAD

**Issue by pbzona** [pathbreak/storm-linode#6]
Line 257 of `cluster_manager.sh` echoes:

"Cluster Manager is ready. Log in using 'SSH_AUTH_SOCK=0 ssh -i ~/.ssh/clustermgr clustermgr@xx.xx.xx.xx'"

This command works, but further configuration may be needed by root, depending on the chosen settings. In addition, the guide's instructions direct the user to log in as root prior to logging in as clustermgr. If a user is following the guide, they may try to perform the security configuration as `clustermgr`, which does not yet have a sudo password. Would you consider changing this to either be nonspecific ("Log in using 'SSH_AUTH_SOCK=0 ssh -i ~/.ssh/<key> <user>@xx.xx.xx.xx'") or, less ideally, direct the user to log in as root initially?

**Comment by pathbreak** [comment]
@pbzona Thank you for reporting. 

I didn't want to duplicate parts of the docs in code. I changed it to report just the Cluster Manager's public IP to keep it simple, since detailed steps are available both in the README and in Linode's docs.

**Comment by pathbreak** [comment]
Closed in release-0.3.0
